### ISSUE TITLE
Doesn't works on Debian 9 Stretch

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/python-shout#1]
Under Debian 9 Stretch @ 64 bits: 
```
# python http://example.py  ../ATB\ -\ Don\'t\ Stop.mp3
Using libshout version 2.3.1
opening file ../ATB - Don't Stop.mp3
Erreur de segmentation
```

I try with Debian 8 Jessie @ 64 bits and it's works well.

**Comment by yomguy** [comment]
Hi @ChoiZ 
0.2.5 is now compatible to Stretch and Buster
cheers ;)
G
