### ISSUE TITLE
SystemError: bad call flags with python 3.8

### ISSUE THREAD

**Issue by printpagestopdf** [yomguy/python-shout#5]
When using the example code I am getting:
    s.open()
SystemError: bad call flags

could that be related to:
https://bugs.python.org/msg348804

**Comment by yomguy** [comment]
Hi @printpagestopdf 
Thanks for the report. I will debug this in a few days.

**Comment by printpagestopdf** [comment]
Hi,
thank your for the answer, Ubuntu 20.04 will have python 3.8 as default - and by the way I am using your library at the moment with 3.6 and it works like a charm, thank you for this!

Best RegardsReinhold

    Am Mittwoch, 22. April 2020, 09:33:37 MESZ hat Guillaume Pellerin <notifications@github.com> Folgendes geschrieben:  
 
 


Hi @printpagestopdf
Thanks for the report. I will debug this in a few days.

**Comment by el07694** [comment]
Any progress?

**Comment by ideoforms** [comment]
I also encountered this bug. I've looked into it and have created a fix in this PR:
https://github.com/yomguy/python-shout/pull/8

@yomguy Thanks for all of your work on this library, it's fantastic!

**Comment by yomguy** [comment]
Hi, thanks a lot @ideoforms for this PR!
@el07694 could you try on your side?

**Comment by printpagestopdf** [comment]
Sorry, a bit late, but I can confirm, that it works like a charm on ubuntu 20.04 LTS.

Best Regards
