### ISSUE TITLE
how to use with shoutcast

### ISSUE THREAD

**Issue by patricktst** [yomguy/python-shout#6]
how to use with shoutcast and example souce code, thanks you

**Comment by yomguy** [comment]
hi @hocptit I have not tested shout with shoutcast but it should work as it has the same API than icecast. Could you try with the help of [DeeFuzzer](https://github.com/yomguy/DeeFuzzer)  make us some feedback?

**Comment by hocptit** [comment]
> hi @hocptit I have not tested shout with shoutcast but it should work as it has the same API than icecast. Could you try with the help of [DeeFuzzer](https://github.com/yomguy/DeeFuzzer) make us some feedback?

Thanks you
